permalink: pretty

theme: jekyll_patternbot

patternbot:
  title: "My Porfolio"
  description: "This website will highlight my skills and show my work"
  font_url: https://fonts.googleapis.com/css?family=Open+Sans:400,700&display=swap
  colors:
    background: "--color-primary-light"
    accent: "--color-primary-dark"
  rationales:
    typefaces.primary:
      Open Sans was selected because I wanted a font similar to Helvetica. I picked this font for its neutral, yet friendly appearence. It is perfectly legible and is optimized for the web, mobile interfaces and print. I appreciate its simplicity and strong visual impact.
